{% set version = '1.1.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-box
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/box_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/box/box_{{ version }}.tar.gz
  sha256: a2fc09bd5a7101b82efabe35427038787fbe671cbdc9805fc193f643f47a1b5b

build:
  merge_build_host: True  # [win]
  skip: True              # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  requires:
    - r-testthat
  commands:
    # package is not supposed to be imported, hence no library('box') test
    - $R -e "testthat::test_package('box')"           # [not win]
    - "\"%R%\" -e \"testthat::test_package('box')\""  # [win]

about:
  home: https://klmr.me/box/, https://github.com/klmr/box
  license: MIT
  summary: A modern module system for R. Organise code into hierarchical, composable, reusable
    modules, and use it effortlessly across projects via a flexible, declarative dependency
    loading syntax.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
